version: '2'
services: 

 mysql:
  image: mysql/mysql-server
  restart: always
  hostname: mysql
  environment:
   - MYSQL_ROOT_PASSWORD=my-secret-pw
  volumes:
   - ./mysql_data:/var/lib/mysql/
   - ./conf/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql

 traccar:
  image: traccar/traccar:4-debian
  hostname: traccar
  restart: always
  ports:
   - "5013:5013"
   - "8082:8082"
  volumes:
   - traccar-db:/opt/traccar/data/database
   - ./conf/traccar.xml:/opt/traccar/conf/traccar.xml

volumes:
 traccar-db:
