version: '2'
services:

 https:
  image: steveltn/https-portal
  ports:
   - "80:80"
   - "443:443"
  links:
   - traccar
  restart: always
  volumes:
   - https:/var/lib/https-portal
   - https:/var/www/vhosts
  environment:
#  - STAGE=local
   - STAGE=production
   - WEBSOCKET=true
   - DOMAINS=${HOSTNAME} -> http://traccar:8082

 mysql:
  image: mysql
  restart: always
  hostname: mysql
  environment:
   - MYSQL_ROOT_PASSWORD=my-secret-pw
  volumes:
   - mysql:/var/lib/mysql/
   - ./conf/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql

 traccar:
  image: marcelmaatkamp/traccar-server
  hostname: traccar
  restart: always
  ports:
   - "5000-5150:5000-5150"
  volumes:
   - traccar-db:/opt/traccar/data/database
   - ./conf/traccar.xml:/opt/traccar/conf/traccar.xml

volumes:
 traccar-db:
 mysql:
 https:
